# Math @365 Data Science

print(<param>)
= Use for print out

type(<param>)
= Use for check **Data Type**

.shape
= Use for find *Data Shape* **Column and Row Matrices**

.reshape
= Use for change shape of some variable


## Scalars
scalar is 1 element
### ***1x1***

In [12]:
s=5
print(s,'\n'
      ,type(s))


5 
 <class 'int'>


## Vector
vectors is collection of scalars
### **1 x n-scalars**

In [13]:

import numpy as np
v = np.array([2,3,4])
print(v,'\n',
      type(v),'\n',
      v.shape)

[2 3 4] 
 <class 'numpy.ndarray'> 
 (3,)


## Matrices
Matrices is collection of vectors
### ***n-vectors x n-vectors***

In [14]:
import numpy as np
m = np.array([[2,1,4],[3,1,6]])
print (m, '\n',
       type(m),'\n',
       m.shape)

[[2 1 4]
 [3 1 6]] 
 <class 'numpy.ndarray'> 
 (2, 3)


## Tensors
Tensor is collection of matrices
### ***n-matrices x n-matrices***

In [26]:
import numpy as np
#creating a tensor
m1 = np.array([[3,1,6],[2,4,5]])
m2 = np.array([[2,5,2],[5,4,2]])
tensor = np.array([m1, m2])
print(tensor,'\n',
      'Shape = ',tensor.shape)
#creating tensor manually
tManual= np.array([[[2,1,3],[3,4,5]],[[5,2,3],[3,4,0]]])
print(tManual,'\n',
    'Shape = ',tManual.shape)

[[[3 1 6]
  [2 4 5]]

 [[2 5 2]
  [5 4 2]]] 
 Shape =  (2, 2, 3)
[[[2 1 3]
  [3 4 5]]

 [[5 2 3]
  [3 4 0]]] 
 Shape =  (2, 2, 3)
